### PR TITLE
uInverter PCB layout review

### PR DESCRIPTION
**Pull request by purohitparth25**
This PR outlines the changes made to PCB layout for revB uInverter board. A majority of the PCB layout is carried over from the revA uInverter design and the changes listed in the [revB update PR](https://github.com/Severson-Group/AMDC-Hardware/pull/198) are incorporated into this revB PCB.

#### Board top layer - 2D view:
image

- Small DC link SMD ceramic decoupling capacitor footprint added
- `0603` component footprints replaced with `0805` footprints
- Cutout provided for using current probe/Rogowski coil for phase current measurement
- Screw connectors removed
- Two decoupling capacitors (`10 uF` and `0.1 uF`) provided for gate driver decoupling
- Decoupling capacitors for gate drivers directly connected to the `Vcc plane` and `Ground pin` of gate driver (instead of connecting to the ground through a `via` in revA)

#### Top and bottom layer layout (minor layout changes from revA) :
Board_2d_sidebyside

#### Option 1 for placing gate driver decoupling capacitor:
Option1_combine

Trace width for option 1 = 20 mil.

#### Option 2 for placing gate driver decoupling capacitor:
Option2_combine

Trace width for option 2 = 40 mil.

#### Option 3 for placing gate driver decoupling capacitor:
Cap_option3

Trace width for option 3 = 40 mil.

[Heat sink](https://www.digikey.com/en/products/detail/aavid-thermal-division-of-boyd-corporation/529702B02500G/1625478) slot height = 3.18 mm
Maximum thickness of capacitors ([0.1 uF](https://www.digikey.com/en/products/detail/kemet/C0805C104K6RAC7800/8572453) and [10 uF](https://www.digikey.com/en/products/detail/murata-electronics/GRM21BR6YA106KE43L/5027598)) = 0.88mm and 1.45 mm (Including tolerance)

#### Snippet of board cutout for probing using a clamp (Teledyne LeCroy CP030) with dimensions:
slot_dimensions

#### Teledyne LeCroy CP030 Probe head dimensions:
Probe head

#### Trace lengths:

Trace length matching is done for all three phases for balanced phase inductance and resistance.

#### Mounting hole spacing:
image

#### 3D view of the assembled board:
image

### CODE REVIEW

**Comment by elsevers** [comment]
Thanks Parth. I am concerned that the traces for your decoupling capacitors on the MOSFET gate drivers are too long and skinny. That is going to add parasitic inductance which will decrease their effectiveness.

**Comment by purohitparth25** [comment]
> 

I had to put those traces to GND pin of the gate driver to avoid a via to GND plane on bottom layer. I have included a connection option 2 with the capacitors closer to gate driver and connected with wider traces.

**Review by elsevers — CHANGES_REQUESTED** [review]
- [x] Remove thermal relief from bypass capacitors on gate driver. Do this by adding the components to an exception list
- [x] Need to add a note in the markdown documentation explaining that if the heat sink is substituted, need to selected a component with space for the bypass capacitors
- [x] Increase board width to ~4mm for current measurement
- [x] Calculate heat rise in the phase current trace
- [x] Move differential amplifier decoupling capacitor closer to the pins
- [x] DC decoupling capacitors: place one large and one small one at each end of the board
- [x] Make spacing between heatsinks symmetrical
- [x] Move vsense trace so that it does not go underneath all of the power traces. 
- [x] Move voltage divider and filter to be placed right at the connector where vsense leaves to go to the AMDC
- [x] Relocate some of the traces on the bottom layer of the board to prevent the ground pore from being disrupted so much
- [x] Clean up routing on neutral

**Review by elsevers — CHANGES_REQUESTED** [review]
- [x] Add note about heatsink cut out for decoupling capacitors to mechanical layer of Altium files AND in the `revxxxxxxB` that you will create for the release of this.
 
- [x] Make traces from decoupling capacitors to differential amplifier pins shorter and straighter to minimize parasitic inductance.

- [x] Move mounting hole spacing so that they fit on a grid pattern

- [x] Adjust phase trace length to be the same for all phases (try using the `trace length tuning` or `length matching` tool in Altium)

**Comment by purohitparth25** [comment]
This PR is ready for review. I have made all the recommended changes

**Review by npetersen2 — COMMENTED** [review]
I reviewed the file structure and changes made, it looks good to me.

I did not open Altium and review the routing changes from last time in detail.

**Review by elsevers — APPROVED** [review]
Nice job!

**Pull request merged**
