### PR TITLE
[DAC Board] Rev C Design Review #1 - Schematic

### PR DESCRIPTION
**Pull request by codecubepi**
## Revision C Overview

This PR is for the first Design Review of Revision C of the DAC Board, focused on the schematic primarily, but also on the new component placement on the PCB.

Two major fixes have been addressed in the Revision C design:

- Replacement TVS diode components have been implemented to fix voltage readout errors caused by the previous TVS diodes in the design (see #204)

- The 15-pin connector circuitry has been updated to allow the DAC expansion board to connect to the AMDC via either the PowerStack or the GPIO Ports, replacing the "IsoSPI" connection interface from DAC Rev B (see #200)

### Output Connectors Schematic - New TVS Diodes
image

### Input Connectors Schematic - New 15-Pin Connector Circuitry
image

#### Top - See U2, C3, C4
image

#### Bottom - See U13, C42
image

## BOM Details

Estimated cost per board is $91.91 with parts from DigiKey. See the BOM [here](https://github.com/Severson-Group/AMDC-Hardware/files/8375839/DAC_Rev_C_BOM_review.xlsx).

### CODE REVIEW

**Review by npetersen2 — CHANGES_REQUESTED** [review]
Thanks @codecubepi !

A few comments:
- Can you confirm pins 4 and 12 of `U13` should be shorted together to the `AMDC_GND` ? I believe only one of these pins should be connected per the datasheet
- I believe there is an issue for the signals going to `U13` when the DAC is plugged into the Power Stack port. In this case, `GPIOX_OUT1..2` are still routed to `U13`, however, they will be connected to the connector `CON1A` which connects to the power stack power signals. This isn't good since, for example, `VPS` should be 24V or 48V relative to `PSGND` which probably would damage `U13`. Can you review this type of issue, i.e. what happens when the DAC is plugged in for either connector type, and check for other problems? One solution is simply to add more jumpers to physically disconnect unwanted signals. Perhaps using the DIP switch idea might make more sense as the number of jumpers increases.

**Comment by codecubepi** [comment]
@npetersen2 

Yeah I think a dip switch ([like this one?](https://www.digikey.com/en/products/detail/cts-electrocomponents/219-6LPSTR/5224124)) would be a simple way to cut off those signals to U13.

And I'm not sure I 100% understand the AM26 G/~G pins... would I just connect ~G to GND? We want it to operate all the time right? Or am I not understanding the purpose of those pins?

**Comment by npetersen2** [comment]
@codecubepi 

- Yes, a DIP switch like the one you linked looks nice.
- Per the `AM26C32` datasheet on page 1 and 8 and 9:

image

image

image

I believe, in your schematic, you tie both `G` and `!G` low, meaning that you have selected `ACTIVE LOW` mode. This means that when the differential voltage between `A` and `!A` is positive, the output is logic 1, and vice versa.

Please confirm the setting for how this is configured on the TX side on the AMDC and confirm the TX and RX sides are configured the same

**Comment by codecubepi** [comment]
@npetersen2  Okay, I added the SDA06H0SBR 6-position DIP switch to allow the cutoff of the Power Stack signals to prevent damage to U13.

I've also tied only the !G signal to GND on the DAC board's U13 sig-diff. It now matches the AMDC's AM26C32 sig-diff components.

image

Please review when you can, and I'd definitely like to meet to go over the PCB trace routing. It's spaghetti to me...

**Review by npetersen2 — APPROVED** [review]
Thanks @codecubepi !

Looks good to me. Let's merge this into `dac-rev-c` branch and move onto the PCB layout.

**Pull request merged**
