### PR TITLE
I/O Converter REV A PCB Review

### PR DESCRIPTION
**Pull request by BrandtBuchda**
This PR is to approve the PCB of the I/O Converter expansion board REV A and merge with develop. The purpose of the the I/O Converter board is convert the the differential I/O from the IsoSPI port on the AMDC to single ended digital I/O.

## Specifications

There are 2 differential inputs and outputs and 2 single ended digital inputs and outputs. The single ended digital outputs are duplicated for a total of 4 differential I/O and 6 single ended digital I/O.

## Schematic

The final version of the schematics is located [here](https://github.com/Severson-Group/AMDC-Hardware/blob/f1e048466425fceacd1ec60499f1db3b7b47c06d/Accessories/ExpansionBoard_IO_Converter/REV20201011A/IO_Converter_sch.pdf).

## PCB Layout

| Dimensions |   |
|:------------------------:|:-:|
| Board Size (W x H) | 2.5" x 1.25"|
| Number of Layers | 2 |

Top layer copper routing:
image

Bottom layer copper routing
image

3D view:
image

### Bill of Materials

| Quantity | Comment           | Supplier Part Number 1 | Designator                                        | Value | Supplier Order Qty 1 |
| -------- | ----------------- | ---------------------- | ------------------------------------------------- | ----- | -------------------- |
| 12       | CC0603KRX7R8BB104 | 311-1341-1-ND          | C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12 | 0.1uF | 12                   |
| 1        | ICD15S13E6GX00LF  | 609-2801-ND            | CON1                                              |       | 1                    |
| 1        | 1935200           | 277-1581-ND            | CON2                                              |       | 1                    |
| 1        | AM26C31IPWR       | 296-30087-1-ND         | U1                                                |       | 1                    |
| 4        | SN74LVC1T45DBVR   | 296-16843-1-ND         | U2, U3, U5, U6                                    |       | 4                    |
| 1        | AM26C32IPWR       | 296-30088-1-ND         | U4                                                |       | 1                    |
| 1        | TLV73333PDBVR     | 296-40673-1-ND         | U7                                                |       | 1                    |

The parts cost about $10 per board at order quantity 1 from Digi-Key.

### CODE REVIEW

**Comment by BrandtBuchda** [comment]
@elsevers @npetersen2 Here is a list of changes I have completed since the previous design review:
- Added voltage level translators to each of the single ended digital I/O.
- Added a single 3.3V LDO for the voltage level translators
- Renamed the signals to general purpose instead of SPI and added annotation for the direction of signals
- Increased the length of the board by 1 inch to 2.5 inches to accommodate the extra IC's and also to add another mounting hole for easier and more secure mounting

**Review by npetersen2 — COMMENTED** [review]
@BrandtBuchda Looking good. I think the PCB is shaping up nicely.

1. Please change the BOM format to CSV so that it can be viewed on GitHub and version-controlled nicely.
2. Please create the `docs/README.md` file. Since this board is so simple, I think just a simple block diagram would be sufficient.

**Comment by BrandtBuchda** [comment]
> @BrandtBuchda Looking good. I think the PCB is shaping up nicely.
> 
> 1. Please change the BOM format to CSV so that it can be viewed on GitHub and version-controlled nicely.
> 2. Please create the `docs/README.md` file. Since this board is so simple, I think just a simple block diagram would be sufficient.

**Comment by BrandtBuchda** [comment]
@npetersen2 I changed the BOM format to CSV, should I add the mardown BOM [here](https://github.com/Severson-Group/AMDC-Hardware/tree/307db37d1c92504799b9a9b266ce5c10bfe7270c/Accessories/ExpansionBoard_IO_Converter/REV20201011A) for convenience? The [`docs/README.md`](https://github.com/Severson-Group/AMDC-Hardware/tree/307db37d1c92504799b9a9b266ce5c10bfe7270c/Accessories/ExpansionBoard_IO_Converter/docs) is completed as well.

**Review by npetersen2 — APPROVED** [review]
@BrandtBuchda I think just including the CSV BOM is good.

Board looks good to me.

@elsevers can now approve, then you can order!

**Review by elsevers — APPROVED** [review]
Looks good @BrandtBuchda. Go ahead and order.

**Pull request merged**
