### PR TITLE
AMDC Test Board development

### PR DESCRIPTION
**Pull request by npetersen2**
This PR introduces the [REV A](https://github.com/Severson-Group/AMDC-Hardware/tree/test-board/Accessories/TestBoard/REV20200620A) version of the AMDC Test Board. This test board is designed to validate the functionality of the power stack and analog interfaces on the AMDC.

## Docs

Read about the test board design in the [`docs/`](https://github.com/Severson-Group/AMDC-Hardware/tree/test-board/Accessories/TestBoard/docs) folder.

## Schematic

The final schematic is located [here](https://github.com/Severson-Group/AMDC-Hardware/blob/test-board/Accessories/TestBoard/REV20200620A/Schematic.pdf).

## PCB

Top layer copper routing:

image

Bottom layer copper routing:

image

3D view:

image

### PCB Fab

The PCB is 2-layer, 3" x 3.9". This can be ordered from PCBWay, $5 for 10 copies (+ shipping).

### Bill of Materials

In qty 10, the components of each board cost $25 on Digi-Key.

### CODE REVIEW

**Review by ngadiyar93 — DISMISSED** [review]
This looks good to me.

**Review by mimayberry — DISMISSED** [review]
I think this all looks pretty good. It would be nice to see more of a 'tutorial' in the documentation down the road.

**Comment by npetersen2** [comment]
Implemented changes from design review meeting. Ready to merge and place POs.

### Changes

1. Add "Install one jumper only!" to PCB silkscreen
2. Add standoffs + screws to BOM
3. Add recommended cables to REV A design output README file

### Final PCB Rendering

image
image

@elsevers Please review, approve, and merge (deleting branch). I will then place POs for qty 10.

**Review by elsevers — APPROVED** [review]
Great! Let's order it.

**Pull request merged**
