### PR TITLE
uAMDC Schematic Review

### PR DESCRIPTION
**Pull request by psinha25**
## uAMDC Overview
This PR is the schematic design for the micro AMDC (uAMDC) project. The `uAMDC` platform is a low-cost "little brother" to the main `AMDC` platform. It uses a [STM32H753](https://www.digikey.com/product-detail/en/stmicroelectronics/STM32H753ZIT6/497-18568-ND/8257856) DSP, an inexpensive ($13) high-performance single-core ARM Cortex-M7 microprocessor, and a [Lattice iCE40 HX4K FPGA](https://www.digikey.com/products/en?keywords=220-1572-ND) that is reasonably powerful and inexpensive ($6). 

The BOM costs roughly $275 per board in quantity 10. However, the cost has not been optimized yet and could probably decrease to $200-$250 per board. 

The `DSP` and `FPGA` will communicate via the DSP's Flexible Memory Controller (FMC), an internal controller that allows the `DSP` to connect to external memories, including SRAM, PSRAM, SDRAM, NOR Flash, and NAND Flash. Upon startup, there is a configuration SPI bus that will be used to send a bitstream from the `DSP` to the `FPGA`. Additionally, there will be an 8-bit address bus and an 8-bit data bus between the `DSP` and `FPGA`. This will allow for faster communication than a normal SPI bus. However, a normal SPI bus has also been electrically connected between the two as a backup communication interface. 

## uAMDC Block Diagram
Screen Shot 2020-08-09 at 6 17 43 PM

## uAMDC PCB Screen Captures
uAMDC_3D
PCB_2D

## uAMDC Links
Below are the links to:
- [uAMDC.pdf](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-sch/uAMDC/uAMDC_sch.pdf)
- [BOM](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-sch/uAMDC/uAMDC_BOM.csv)
- [PCB 3D screen capture from Altium](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-sch/uAMDC/uAMDC_3D.JPG)

## uAMDC vs. AMDC
Below is a list of the similarities and differences between the `uAMDC` and `AMDC` schematics.

### Brand New Schematics
- `uAMDC.SchDoc`
- `DSP.SchDoc`
- `FPGA.SchDoc`
- `Ethernet.SchDoc`
- `SWD.SchDoc`
- `USB.SchDoc`

### Slightly Modified Schematics
- `GPIO.SchDoc`
- `Power.SchDoc`
- `DriveInterface.SchDoc`
- `InverterTranslation.SchDoc`
- `InverterConnectors.SchDoc`
- `InverterConnector.SchDoc`
- `FPGA_IO.SchDoc`
- `BackPage.SchDoc`

### Unchanged Schematics
- `LVHV8ChanTranslation.SchDoc`
- `TranslationDir8Chan.SchDoc`
- `Encoder.SchDoc`
- `AnalogInterface.SchDoc`
- `AnalogADCs.SchDoc`
- `AnalogConditioning.SchDoc`
- `AnalogSigCond.SchDoc`
- `AnalogConnectors.SchDoc`
- `USB_UART.SchDoc`
- `isoSPI.SchDoc`
- `Power_InrushLimit.SchDoc`
- `Power_Protection.SchDoc`

### CODE REVIEW

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@psinha25 Nice work today! I think this PR is almost ready to merge, pending a couple things:

1. I noticed the `altium/` folder has some schematic docs in it that are not in the uAMDC design: e.g. `JTAG`. Can you remove the unneeded files? Also, you have `uAMDC2` vs `uAMDC` etc
2. Can you put a little bit of info in the main `README` file? You can use parts from your PR and the summer planning doc for inspiration.
3. Can you move the "compiled" output files into a `REVxxA` folder? This includes the BOM, PDF of schematics, and 3D screenshot image.

**Comment by npetersen2** [comment]
I have captured the Ethernet PHY review in issue #139, we we can merge this PR once @psinha25 gets the above listed items done.

**Comment by psinha25** [comment]
@npetersen2 I made the following changes per your requests: 
1. Removed schematic documents that are not part of the `uAMDC` design
2. Provided information in the `README` about the `uAMDC` project
3. Created a `REVxxA` folder and moved the BOM, screen capture of 3D PCB, and PDF of the schematics.

**Review by npetersen2 — APPROVED** [review]
Looks good! PCB layout time :)

**Pull request merged**
