### PR TITLE
uInverter revision C

### PR DESCRIPTION
**Pull request by purohitparth25**
This PR details modifications made in uInverter revC board

### CODE REVIEW

**Comment by purohitparth25** [comment]
@elsevers @npetersen2 
As discussed today, I have created this PR for `revC` board that has the `silkscreen designators` fixed.

**Comment by purohitparth25** [comment]
- [x] List all the changes with narrative, mention that this is a draft PR
- [x] Add gerbers, fab files
- [x] Add 3D rendering photo for rev C

**Comment by purohitparth25** [comment]
The uInverter `rev C` incorporates following changes:

(**Note**: These changes are non-functional changes and the PR will remain as a `draft` PR until any functional changes are made to the `rev C`)

### 1. Fix silkscreen designators:
In the uInverter revB, silkscreen annotation was done using a crude Re-annotate feature to avoid printing channel names in component designators. However, the component designators in the schematic and the BOM have channel names which caused mismatch between the designators in BOM/Schematic and the PCB silkscreen.

The the `silkscreen designators` are fixed to match with the `schematic` and the `BOM` (fixes Issue https://github.com/Severson-Group/AMDC-Hardware/issues/216)

PCB silkscreen designator format changed to a more appropriate `$Component$ChannelAlpha` form.

Before:
image

After:

image

### 2. Fix PWM testpoint designators on the silkscreen

Fixed PWM testpoint designator from `PWM-A1$ChannelAlpha` to `PWM$ChannelAlpha`

### 3. Fix sheet designator names in the main schematic page

The schematic sheets on main schematic page were not numbered, resulting into random mapping between the phases and the sheets.

Before:

image

After:

image

Following is the mapping between phases and sheets after numbering sheet designators:
- Phase A --> U_Half_bridge_load1
- Phase B --> U_Half_bridge_load2
- Phase C --> U_Half_bridge_load3

**Comment by purohitparth25** [comment]
@elsevers @npetersen2 

I added a narrative for the modifications made in `rev C` and also added the fab files for the project.

@anirudhupadhyaya , you can now clone this branch to verify if everything looks ok to you for `rev C`

**Review by npetersen2 — COMMENTED** [review]
@purohitparth25 I reviewed your narrative above and it looks good to me.

I also reviewed the files changed, and it also looks good.

**Review by anirudhupadhyaya — COMMENTED** [review]
@purohitparth25, I have reviewed the silkscreen designators after cloning the branch. They look good to me.

**Review by elsevers — APPROVED** [review]
Looks good, thanks @purohitparth25! Let's order these.

**Pull request merged**
