### PR TITLE
Knob board rev a sch

### PR DESCRIPTION
**Pull request by wknutson**
Schematic is likely function, however it can be simplified. Specifically 2 of the 10 K resistors around the encoder can be removed if the current schematic is functional.

### CODE REVIEW

**Review by npetersen2 — CHANGES_REQUESTED** [review]
Thanks @wknutson ! Looking pretty good! A few comments and requests:

- [x] Change title block to have correct board revision ("A") and your name for Engineer field
- [x] Add text labels next to DB-9 and DB-15 connects which indicate which AMDC port they connect to, e.g. "To Encoder on AMDC" and "To GPIO on AMDC"
- [x] DB-9 pin-out looks great; matches AMDC's encoder pin-out
- [x] DB-15 pin-out looks great; matches AMDC's GPIO pin-out
- [x] Tidy up designator labels for `JP1` and `JP2`
- [x] Add part number for `C3` 
- [x] Add part number for resistors and capacitors supporting the encoder
- [x] Revise encoder `A` and `B` pin's supporting circuitry to match datasheet; encoder pins should not be connect directly to `U1`, instead should go through a resistor
- [x] Revise encoder switch support circuitry: think about when the switch goes from closed to open. How long will it take for the input to `U1` to see the change? HINT: I believe it was take too long (or, unknown time), so update the circuitry by adding a resistor to fix

**Comment by wknutson** [comment]
Schematic Review PDF

[Schematic Review.pdf](https://github.com/Severson-Group/AMDC-Hardware/files/8466944/Schematic.Review.pdf)

**Comment by npetersen2** [comment]
Thanks @wknutson 

I am approving this schematic PR so you can get the PCB layout finished in the new PCB layout PR.

My only comment on your schematic is to potentially change the voltage divider on the encoder output to ensure the `ON` voltage is sufficiently high. As it is now, the `ON` voltage from the encoder is just 50%, but by using a 100k resistor, you could increase the `ON` voltage to ensure `U1` sees the voltage transitions as valid.

**Review by npetersen2 — APPROVED** [review]

**Comment by npetersen2** [comment]
Please merge this PR and delete this branch. Then, create your new PCB layout branch and PR so we can review your PCB before ordering the board!

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@wknutson I am providing PCB layout comments here on this PR since you are working on the layout.

- [x] I checked the schematic and it is looking good.
- [x] Run a Design Rule Check (DRC) in Altium and verify there are no issues. I found an issue with `C3` -- there is a small track present which shouldn't be there:

image

- [x] Add a `REVxxxxxxxxA` label to your board in the silkscreen
- [x] Update the board size to be a nice number: it is currently 80mm by 78.957mm, please change to be a round mm size
- [x] Add a label to the silkscreen near the `CON2` and `CON1` which indicate which port on the AMDC it should plug into, i.e. "To AMDC Encoder" vs "To AMDC GPIO" etc
- [x] Add the board outline to the Mechanical 1 layer. Do this via the menu below:

image

Please make these updates ASAP and ping me so we can get this board finalized, merged into `develop` and ordered! Thanks

**Comment by npetersen2** [comment]
Looks like this PR is old and should be closed in favor of the PCB PR: #214 which includes all the same contents.

There will probably be Altium merge conflicts if we merge this PR first and then try to do #214

**Review by elsevers — CHANGES_REQUESTED** [review]
Looking good! Schematic change requests:

- [x] Add 0's in front of decimal  capacitor values -- i.e. `0.1uF`
- [x] Remove Digikey part number above C4

**Comment by npetersen2** [comment]
Closing in favor of new PR #214 -- all the changes from this PR have been manually moved to the other PR

**Pull request closed without merging**
