### PR TITLE
Fix component designators on uInverter revB PCB silkscreen

### LINKED ISSUE #216: uInverter: silk-screen designators and schematic designators mismatch
Designators do not match between the schematic and silk screen for many BOM items.
Attached representative image showing mismatch for the decoupling caps.

uInverter_marked
uInverter_InputPower

### PR DESCRIPTION
**Pull request by purohitparth25**
This PR fixes Issue #216 .

In the `uInverter revB`, silkscreen annotation is done using a crude `Re-annotate` feature to avoid printing channel names in component designators. However, the component designators in the schematic and the BOM have channel names which caused mismatch between the designators in BOM/Schematic and the PCB silkscreen.

Fixed in this PR:
- PCB silkscreen designator format changed to a more appropriate `$Component$ChannelAlpha` form

Before:
image

After:

image

- Fixed PWM testpoint designator `PWM-A1$ChannelAlpha` to `PWM$ChannelAlpha`
- Fixed sheet designator names in the main schematic page

Before:

image

After:
image

### CODE REVIEW

**Comment by purohitparth25** [comment]
@elsevers 
This PR is ready for review and discussion.

**Comment by purohitparth25** [comment]
@anirudhupadhyaya @mslaffin @shamagvasisht 

Can you please verify if the silkscreen designators match with the Schematic/BOM sheet? Thanks!

**Comment by mslaffin** [comment]
Labelling the phase on the silkscreen makes it much more readable. Looks good to me.

**Comment by purohitparth25** [comment]
@purohitparth25 Make 2 PRs:
- [x] Modify BOM in revB folder - add column to map schematic designators and silkscreen designators
- [x] Another PR for revC with the fixed silkscreen designators

**Comment by purohitparth25** [comment]
Refer to following PRs created to incorporate the above changes:
1. https://github.com/Severson-Group/AMDC-Hardware/pull/220
2. https://github.com/Severson-Group/AMDC-Hardware/pull/221

**Pull request closed without merging**
