### PR TITLE
uAMDC PCB Layout Review

### PR DESCRIPTION
**Pull request by psinha25**
This PR highlights the placement of all the components on the `uAMDC` board. Please note that the routing has not been completed yet, but the components and silkscreen have been placed. The orientation of the `uAMDC` board (which way to view the board) is the same as the `AMDC` REVD board. The components on the `uAMDC` are placed in the same relative areas as the `AMDC` REVD board, with slight changes in the location of the host interface. 

The cost of the PCB (in quantity 10) is $11.30 per board and the cost of the BOM (in quantity 10) is $289. The total price is about $300.

## Board Shape and Size
The overarching `uAMDC` board size is 4.34 x 5.12 inches. The shape and size of the `uAMDC` board were determined based on the requirement that most (if not all) mounting holes should be in the same location as the `AMDC`. There were two board shape options that were being considered and they are shown below. Thick white silk screens were drawn on the `AMDC` board to show the relative size of the `uAMDC` to the `AMDC`.

1. Dimensions: 3.55 x 6.00 inches. The `uAMDC` board would cover up the right side of the thick silk screen line that runs across the `AMDC` board.

option2

2. Dimensions: 4.34 x 5.12 inches. The `uAMDC` would cover the right and bottom of the thick silk screen lines that are on the `AMDC`.

option1

The second option was chosen for two key reasons: 
1) Routing with the second option would not be as messy as routing on the first option because the `DSP` subsystems would be close to the `DSP` and the `FPGA` subsystems would be close to the `FPGA`. There wouldn’t be any overlap.
2) The shape of the board is not “awkward” with the second option. The first option would result in a long and skinny board shape.

## uAMDC and AMDC Overlay
The screen capture below (requested specifically by Professor Severson) is meant to overlay the `uAMDC` and the `AMDC` to
1) get a sense of the size of the `uAMDC` with respect to the `AMDC`
2) communicate where the location of mounting holes differ between the two boards. 

The bottom right mounting holes are in the same location between the two boards and all the other mounting holes are placed with respect to those on the `uAMDC`. The yellow X represents the location of the mounting holes on the `AMDC`. The mounting holes on the bottom and right side of `uAMDC` are in the exact same location as the mounting holes on the `AMDC`, which is why there isn't a yellow X. 

uAMDC_AMDC_Overlay_2 0

### Top View

3D Top View (1)

2D_Top_View

### Bottom View

3D Bottom View

2D_Bottom_View

### All Layers 2D View

2D_All_Layers

### Corner View 1

Corner View 1 0

### Corner View 2

Corner View 2 0

### Corner View 3

Corner View 3 0

## Attached Files
- [Updated Schematics](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC.pdf)
- [Updated BOM](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC_BOM.csv)
- [Updated 3D PCB Image](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC_3D.JPG)

## Changes in Schematics

There are a few changes that have been made to the schematics. In particular, the following schematic documents were altered: 
1. `Power.SchDoc` - found new parts to replace existing parts that had large footprints
2. `Power_Protection.SchDoc` - replaced a large capacitor with an existing capacitor on the same sheet

Other minor changes throughout the schematic documents include moving nets and net labels, updating various footprints, and just subtle  reformatting. 

## Discussion Topics
1. Is the `uAMDC` board too compact? When moving forward with routing, will it be a nightmare? 
2. Are there any overarching subsystems that should be moved to a different section on the board? 
3. Do the locations of the jumpers need to be relocated? Are there too close to other components? Are they too close to each other? 
4. What other silk screen descriptions are needed? 
5. Are the analog subsystems too compact? What about the ADC?

### CODE REVIEW

**Review by ASHAD1 — COMMENTED** [review]
Nice work @psinha25, I have not reviewed the PCB in detail, but I have some suggestions for schematic.
1. 3.3V supply which is rated for 1A is used to supply power in many places, make sure the rating is fine.
2. I have found the schematic implementation of the ethernet IC used on the board, here is the link http://ww1.microchip.com/downloads/en/DeviceDoc/evb8742_sch.pdf.  It's a good idea to use the same components as in the schematic. Slightly different values component can be used to reduce BOM.
3. You can use the same supply for `VDD1A`  `VDD2A`, and pull up for ethernet `TX` `RX` signals. General 3.3V can be used with ferrite bead as in the [schematic](http://ww1.microchip.com/downloads/en/DeviceDoc/evb8742_sch.pdf).
4. It's a good idea to install capacitors for Ethernet `TX` and `RX` lines as in [schematic](http://ww1.microchip.com/downloads/en/DeviceDoc/evb8742_sch.pdf). This board will be used in high EMI.
5. I don't know if I had missed it. Why is there pull up resistor for `RMII_RX` signals.

**Comment by psinha25** [comment]
This comment documents the changes in the uAMDC board per the feedback from the design review and consolidates links to the documentation.

## Change to uAMDC Board

- Rearranged host interface connectors to exactly match the AMDC board
- Replaced the two 24V/16V DC/DC Converters with one 24/15V DC/dc Converter
- Moved DSP and FPGA decoupling capacitors to top layer of the board to be closer to pins
- Added more silkscreen for jumpers, connectors, etc. 

Below are images of the updated uAMDC board. 
uAMDC_3D

uAMDC_2D_Top

uAMDC_2D_Bottom

uAMDC_3D_Top

uAMDC_3D_Bottom

## Documentation
Below are links to the  uAMDC Documentation
- [README.md](https://github.com/Severson-Group/AMDC-Hardware/tree/uamdc-rev-a-pcb/uAMDC)
- [docs/README.md](https://github.com/Severson-Group/AMDC-Hardware/tree/uamdc-rev-a-pcb/uAMDC/docs)

## Links
- [Updated Schematics](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC.pdf)
- [Updated BOM](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC_BOM.csv)
- [Updated 3D Image](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC_3D.JPG)

**Comment by psinha25** [comment]
This comment of the PR dives deeper into the labyrinth that is the uAMDC routing. There are a couple of key points worth mentioning before moving forward: 
1. The board has been changed from a 4-layer board to a 6-layer board. 
2. The size of the board has not changed and the overall placement of subsystems has not been altered on the uAMDC while routing. 
3. Individual components within subsystems have been shifted and rotated to make it easier to create clean routes. 
4. Pins on the FPGA were reassigned certain nets to decrease overlap. The FPGA was oriented in a manner to ensure that each side was as close as possible to its respective connections. 

The cost of the 6 layer board is $25 per board in quantity 10. The cost of the BOM is $254 per board in quantity 10. 

This PR will be broken down into a a couple different sections: 
1. Pictures of the entire board including routes on all 6 layers (2D and 3D)
2. Analyze the analog subsystem routing
3. Analyze the ethernet subsystem routing
4. Analyze the routing that connects the FPGA and DSP on the uAMDC. 

## uAMDC Repo Links
- [Updated Schematics](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC.pdf)
- [Updated BOM](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC_BOM.csv)
- [Updated 3D Image](https://github.com/Severson-Group/AMDC-Hardware/blob/uamdc-rev-a-pcb/uAMDC/RevxxA/uAMDC_3D.JPG)

## Overview of the uAMDC Board with Routing

Each of the 6 layers are strategically used to route certain signal. 
1. Layer 1 (red) is the top layer, used to route as many of the signals as possible. 
2. Layer 2 is the GND layer. 
3. Layer 3 (orange) is used to route the signals between the individual signals from the subsystems to either the DSP or the FPGA. 
4. Layer 4 (purple) is used to route the signals between the DSP and the FPGA. The layer is also used to route power signals and assist with any other remaining signals that need to be routed. 
5. Layer 5 (light blue) is considered the power layer and is used to route power signals from the LDOs to the individual subsystems. 
6. Layer 6 (dark blue) is the bottom layer, used to route as many signals on the bottom layer as possible. 

Below are different screen captures to get a sense of what the board looks like post routing. Pictures are in 2D and 3D. Because viewing the 2D picture with all 6 layers is tough to digest, screen captures of the routing on each layer has been included as well. 

uAMDC_routing_3D


uAMDC_routing_3D_bottom


uAMDC_6_Layer_Routing

uAMDC_Layer1


uAMDC_Layer3


uAMDC_Layer4


uAMDC_Layer5


uAMDC_Layer6


## Analog Subsystem Routing

This subsystem is being highlighted because of the importance of of the ADC. Below are screen captures of the analog subsystem routing. 

Key discussion points include spacing of the capacitors and resistors around the ADC, the routes from the ADC to the FPGA, and any other potential hazards with the routing (overlap of routes on different layers, etc.). 

analog_6layer


analog_toplayer


analog_3rd


analog_4th


analog_6th



## Ethernet Subsystem Routing

The Ethernet routing is extremely high speed and there are a lot of critical details in ensuring that the routing is proper. Below are the key factors that I took into account when routing: 

1. The routes that are critical and that have very little room for error are the RMII signals from the PHY to the DSP and the four differential pair routes from the Ethernet connector to the PHY. 
2. The RMII signals must be length matched from the PHY pins to the DSP (which means the individual resistors that are between the two must also be included in the length matching process). 
3. The differential pair signals must be length matched and within each pair, the length of the signals must be within 50 mil of each other. 
4. The trace width and gap of the differential pairs should be calculated (used this [calculator](https://www.everythingrf.com/rf-calculators/differential-microstrip-impedance-calculator)) to meet a certain differential impedance (100 ohms). 
5.. Keep the stubs off the differential pair signals as short as possible. 
6. The crystal oscillator into the PHY should be as close to the PHY pins as possible. 

Below is a screen capture of the bottom layer where the Ethernet routing takes place. Vias are used to connected the signals from the PHY to the DSP. 

Ethernet_bottom


## DSP to FPGA Signals

The DSP and FPGA need a high speed communication interface. A couple of options have been routed to provide options for firmware down the line:
1. FMC interface (FMC signals and a configuration SPI interface)
2. SPI interface. 

The pins on the FPGA were strategically placed to decrease overlap between the DSP and FPGA. Unfortunately, this room for flexibility with pin assignments wasn't present on the DSP, but routing was done in such a way as to decrease overlap between signals and create clean routes whenever possible between the two. All the routes on between the DSP and the FPGA were done on the 4th layer (purple layer of the board). 

Below are screen captures of the routing: 

DSP_FPGA


DSP_FPGA_LAYER4

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@psinha9 Very nice! A few things:

1. Let's rename the `REV` output folder to use capitals "REV" since this will match our other repos.
2. Please rename the schematics PDF file to not have two `.pdf` extensions
2. There is an image missing in the `/uAMDC/` main readme file in the GitHub view
3. All the images in the `/uAMDC/docs` main readme file in the GitHub view don't show up.
4. In the BOM, C44 doesn't have a supplier part number listed
5. Please change the `DriveInterface` schematic page to have a pure white background.

**Comment by psinha25** [comment]
@npetersen2 I have updated the PR per your comments.

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@psinha25 Thanks for making those changes.

Last thing: Please create a README.md file which goes in the `REV` output file which describes the board dimensions, number of layers, etc etc. This information is needed for ordering the PCB.

See examples of this for the other boards in the various repos in the group. One good example is Brandt's DAC board: https://github.com/Severson-Group/AMDC-Hardware/tree/develop/Accessories/ExpansionBoard_DAC/REV20200720B

**Comment by npetersen2** [comment]
One more thing, in your markdown docs, please use relative paths for the image links. This will make the links continue to work after we merge this PR in.

**Comment by psinha25** [comment]
@npetersen2 I've made those changes that you requested. TOC and image paths are using relative paths and a README has been created in the REV folder with board information.

**Review by npetersen2 — APPROVED** [review]
Looks good @psinha25 !

@elsevers Please give this a review, then we will `Squash and Merge`. After that, I will submit the PO for the uAMDC! :) Exciting!

**Review by elsevers — APPROVED** [review]
Nice work @psinha25

**Pull request merged**
