### PR TITLE
uInverter revB Schematic Review

### LINKED ISSUE #192: uInverter: Add low pass filter to DC bus voltage sensing
@purohitparth25 found that the DC voltage measurement feedback was pretty noisy.

LeCroy38

#### AMDC Sampled data:

output_10_7

There is no capacitance added at the voltage divider nodes. I think we can easily fix this by adding a small cap (perhaps 100nF or so) between the sense node and GND. We should tune the bandwidth to a reasonable value to not impede control algorithms.

image

### LINKED ISSUE #193: uInverter: Swap polarity of current feedback voltage
When you flow current from the source into the 3-phase load, by motor convention, the current is positive.

However, based on how the sense resistor is hooked up to the difference amplifier, the feedback voltage is negative.

I believe we can simply swap `+` and `-` terminals on the diff amp to solve this--then, positive current would result in a positive voltage feedback signal. I think this makes more sense.

image

### LINKED ISSUE #194: uInverter:Change DC link resistor part no. in BOM sheet
Part number (541-RCS06032K49FKEACT-ND) listed in BOM sheet for a 2.49 K Ohm resistor, however, the resistor in the schematic is a 2.2 K Ohm. Part number in the BOM needs to be updated.

image

### LINKED ISSUE #197: uInverter: Redundant jumper provision to disconnect series R-L load - Simplify design
Present design of `uInverter` has two screw connectors on either side of the series R-L load (`J2` and `J3` in the image), however, to test the current regulation and other algorithms, we need the series `R-L load` anyways and the user would end up shorting out the jumpers at all times. A design simplification can be made by removing the screw connector between the switch node and `R-L load` (Connector `J2`) to simplify the design and provide a test point instead for more flexibility in measurement.

### Half-Bridge schematic - uInverter revA:
image

### LINKED ISSUE #199: uInverter: High DC link current ripple
High ripple is seen in the DC link current even after having a relatively large DC link bulk capacitance of `2000 uF`. Below waveform captures show the input DC current from a benchtop DC power supply at 12 V DC  link voltage. 

#### Waveforms:

image

##### DC-link voltage waveform (300 Hz output fundamental frequency, 3.4 A load current):
LeCroy38

From the waveforms, it looks like the ripple current reduces with an increase in switching frequency and fundamental output frequency.

### PR DESCRIPTION
**Pull request by purohitparth25**
This PR outlines changes in [schematic](https://github.com/Severson-Group/AMDC-Hardware/blob/uInverter_revB_Sch/Accessories/ExpansionBoard_uInverter/Altium) for Rev B uInverter board. Following are the changes incorporated in this revision:

1. The polarity of sensed phase current is reverse because of the inverted connection of differential amplifier as pointed out in issue #193 . In this revision the differential amplifier's input connection is swapped to get the correct polarity of the sensed current.

2. This revision also addresses issue #192 by adding a `0.1 uF` filtering capacitor to filter out the high-frequency noise in DC link voltage measurements. An important thing to consider while placing this capacitor is its sizing. This additional capacitor along with the potential divider network of DC bus voltage sensing will form a low pass filter (see [image](https://user-images.githubusercontent.com/90465550/154992877-4083afe3-0d65-4107-a3f3-8b5635f441ae.png)) and this should not affect the nominal sampling operation of the DC bus voltage.

image

Bandwidth of the low pass filter in this particular configuration is given by:

image

Here, a bandwith of `1 kHz` is desired from this low pass filter and for this case, the capacitor value comes out to be around `100 nF`

##### DC-link voltage waveform (300 Hz output fundamental frequency, 3.4 A load current):
LeCroy38

As it can be seen from the above waveform, the DC-link voltage has two components. The high-frequency component is well beyond the `1 kHz` cutoff frequency, however, the low-frequency ripple is around `900 Hz`, which will be captured at this `1 kHz` cutoff frequency.

3. Revision A uInverter has two screw connectors, however, the user would anyways keep those shorted while using the board as mentioned in issue #197 . In this revision, the screw connectors and a cutout is made in the PCB so that the user can measure currents using a clamp `(LeCroy CP030A Oscilloscope Probe)`.
4. An additional 10 uF ceramic capacitor is added for high frequency noise decoupling at DC link issue #199 

5. 0603 sized packages for `Capacitors: C3, C4, C5, C6 and C7` and `Resistors: R1, R2, R3, R4 and R5` (In attached images) used in revision A are now replaced by 0805 sized packages for ease of board 'Bring-up'

### Rev-A Schematic

Sch_Before

### Rev-B Schematic (Changes highlighted in green boxes):

revB (1)

### Board 3D view:
image

##### Other changes

 - Part number for 2.2K Ohm DC link voltage sensing resistor mentioned in [BOM](https://github.com/Severson-Group/AMDC-Hardware/blob/uInverter_revB/Accessories/ExpansionBoard_uInverter/REV20210506A/uInverter-rev-a_bom.csv) was incorrect as per issue #194, which is corrected in this PR.

### CODE REVIEW

**Comment by elsevers** [comment]
Hello Parth, it looks like the GitHub issues are not yet linked in here. Can you link these?

Screen Shot 2022-02-21 at 8 37 06 AM

**Comment by elsevers** [comment]
Please revise your PR description of item 2 to explain how you have selected this capacitor value (i.e., discuss the filter bandwidth).

I seem to recall you planning to do some additional experimentation regarding DC link noise. Is this still forthcoming?

**Comment by purohitparth25** [comment]
I could not get the DC link current waveforms last week. I am doing that today and will update this PR once collect the data.

**Review by elsevers — CHANGES_REQUESTED** [review]
- [x] Adjust op amp symbol pinout so that rail voltage is on the top of the symbol
- [x] Make `Vcc+` and `Vcc-` ports vertical
- [x] Whenever possible, align `Vcc+`, `GND`, and `Vcc-` 
- [x] Investigate what frequency of noise appears in issue #192 to select appropriate corner frequency of RC filter. Proposal to reduce corner frequency below 1 kHz, but need to verify if this is appropriate.
- [x] Add BOM item for jumper part that fits into jumper that goes to neutral
- [x] Add 16V zener across DC link
- [x] Investigate VA limits of gate driver when 16V zener is installed
- [x] Update part number in Altium to address issue #194 (instead of changing it in the exported BOM file)

**Comment by purohitparth25** [comment]
I have made the requested changes. I skipped the 16V Zener part since we are no longer having screw terminals. Regarding the DC link voltage ripple frequency, as expected there are two components in it. The high-frequency component is well beyond the 1 kHz BW set for the filter, however, the low-frequency component would change with the output fundamental frequency (Can be thought of as a rectified version of the AC output voltage) and may go above 1 kHz at higher output frequency (eg. 700 Hz).

**Review by elsevers — CHANGES_REQUESTED** [review]
- [x] Modify the gate driver decoupling capacitor to match the data sheet recommendation (two X5R ceramic capacitors in parallel: 10 uF and 0.1 uF)
- [x] Eliminate extra nodes in Altium schematic, i.e.:  image
- [x] Modify Altium file names to not have the revision in the name. There should just be a single set of Altium files in the `altium` folder that are used (do not store Altium files in the `revA`, `revB` folders). **Make sure that no files in `revA` folder are changed; there should just be one `altium` folder at the top level of the uInverter directory**
- [x] Add 0805 10 uF capacitor across the DC link
- [x] Start writing a `CHANGELOG.md` file for the uInverter. See the AMDC [`CHANGELOG.md`](https://github.com/Severson-Group/AMDC-Hardware/blob/develop/CHANGELOG.md) as an example.

**Comment by purohitparth25** [comment]
I have made requested changes in the schematic and updated the image in this PR. I have also created a `CHANGELOG.md` in the `uInverter` folder. The PR is ready for review.

**Review by npetersen2 — APPROVED** [review]
Looks good to me! Nice work, @purohitparth25 :)

I'd say you are ready to merge this and complete the PCB layout.

**Review by elsevers — APPROVED** [review]

**Pull request merged**
