### PR TITLE
CAN Board Design Review

### PR DESCRIPTION
**Pull request by psinha25**
This PR highlights the schematics and PCB of the CAN expansion board to the AMDC. The purpose of the CAN board is to provide the AMDC the ability to interface with CAN devices. 

Before diving into the schematics and PCB, there are a key points worth noting: 
- The board is a 2 layer board with a size of about 3" x 2.5".
- All components and silkscreen are on the top of the board
- Most of the routes are on the top layer (only 2 routes on the bottom layer)
- There are two CAN buses on the board, each with their own screw terminals and DB-9 connector

The cost of all the components on the board is about $55. The cost of one board (in quantity 10) is $2.30. 

This PR will be broken down into a couple of different sections: 
1. Schematic Review
2. PCB Review
3. Specific Discussion Points
4. Miscellaneous Items

## Schematic Review
Here is a [link ](https://github.com/Severson-Group/AMDC-Hardware/blob/can-rev-a/Accessories/ExpansionBoard_CAN/REV20201119A/CAN.pdf )to the schematics. It is 4 pages. 

## PCB Review
Below are images of the PCB in 2D and 3D views. 

CAN_2D

CAN_2D_Top

CAN_2D_Bottom

CAN_3D

CAN_3D_Bottom

CAN_3D_Angle1

CAN_3D_Angle2

## Specific Discussion Points
1. Routing
2. Is a resistor connected to shield of DB-9 connector necessary? If so, what ground is one of the pins connected to? 
3. Do the two mounting holes on the right ends of the connector need to be connected to ground? 

## Miscellaneous Items
- [CAN Schematics](https://github.com/Severson-Group/AMDC-Hardware/blob/can-rev-a/Accessories/ExpansionBoard_CAN/REV20201119A/CAN.pdf)
- [CAN 3D Image](https://github.com/Severson-Group/AMDC-Hardware/blob/can-rev-a/Accessories/ExpansionBoard_CAN/REV20201119A/CAN_3D.JPG)
- [CAN BOM](https://github.com/Severson-Group/AMDC-Hardware/blob/can-rev-a/Accessories/ExpansionBoard_CAN/REV20201119A/CAN.csv)

### CODE REVIEW

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@psinha25 Thanks for the updates. A couple things, then we can merge this PR and order the boards:

1. Rename the README files to match the other filenames (i.e. change extension `*.MD` to `*.md`)
2. The main readme has a link to a `docs/` folder. This doesn't seem to work. I don't think there is any docs yet for this board. Can you put together some documentation? It can be minimal and just express the design goals of the board (i.e. 2x CAN, isolated, add CAN to AMDC, etc). See [this doc file](https://github.com/Severson-Group/AMDS/blob/develop/LowVoltageCard/docs/README.md) for an example of minimal docs.
3. I see there are 85 files changed in this PR. However, it looks like the majority of these are changes to the main AMDC files, not the new CAN board. Please update the PR to revert the changes to these files so that the only changed files are related to the CAN board.

**Comment by psinha25** [comment]
After unsuccessfully attempting to revert the file changes that were wrongfully done, I created a new branch `can-rev-a-new` and cherry-picked specific commits that were only relevant to the development of the CAN board. That PR can be found [here](https://github.com/Severson-Group/AMDC-Hardware/pull/153).

**Comment by psinha25** [comment]
@npetersen2 I have made all the changes you have specified in your last comment. Please look to this [PR](https://github.com/Severson-Group/AMDC-Hardware/pull/153) for those changes and the final development of the CAN board.

**Comment by npetersen2** [comment]
Closing this PR in favor of the new PR: #153

**Pull request closed without merging**
