### PR TITLE
ADC breakout board to BNC jacks

### PR DESCRIPTION
**Pull request by npetersen2**
This PR introduces a new breakout board for the AMDC: it converts the 8x analog inputs (RJ45 jacks) to BNC inputs.

## Schematic

The final schematic can be found [here](https://github.com/Severson-Group/AMDC-Hardware/blob/adc-breakout-board/Accessories/ExpansionBoard_ADC_BNC/REV20200806A/Schematic.pdf).

## PCB

The PCB is designed as a simple pass through board from the BNC connectors to the AMDC. Therefore, there is no pours of copper (i.e. GND pour) since these are not needed and would pick up EMI. There are no components on the bottom and no silk screen markers -- the bottom is completely blank.

All analog input signals are routed as diff pairs so that radiated common mode EMI will be rejected (the AMDC analog inputs are fully differential).

image

image

### PCBs

The PCB design uses standard processes, so it will cost $5 per qty 10.

### BOM

The BOM for one board in qty 10 is $30. See the BOM [here](https://github.com/Severson-Group/AMDC-Hardware/blob/adc-breakout-board/Accessories/ExpansionBoard_ADC_BNC/REV20200806A/BOM.md).

### CODE REVIEW

**Comment by elsevers** [comment]
@npetersen2 Does this mean that the cables are transposed when the AMDC and ADC board are facing each other? 

image

**Comment by npetersen2** [comment]
@elsevers Correct.

**Review by Anvar-Khamitov — APPROVED** [review]
Looks great. I think it can be approved.

**Review by elsevers — APPROVED** [review]

**Comment by elsevers** [comment]
Thanks @npetersen2 and @Anvar-Khamitov

**Pull request merged**
