### PR TITLE
IO Converter REV B PCB Review

### PR DESCRIPTION
**Pull request by BrandtBuchda**
This PR is to approve the PCB of the I/O Converter expansion board REV B and merge with develop. The purpose of the the I/O Converter board is convert the the differential I/O from the IsoSPI port on the AMDC to single ended digital I/O for the eddy current sensor. The REV B version of the board directly attaches to the eddy current sensor.

## Specifications

There are 2 pairs of differential inputs and outputs from the AMDC. The differential outputs are converted from 5V diff pairs to 3.3V single ended logic. The IO is routed to the DSUB mini-9D connector for the eddy current sensor SPI. Additionally there is a 4 position terminal block to supply 24V and common GND to the eddy current sensor.

## Schematic

The final version of the schematics is located [here](https://github.com/Severson-Group/AMDC-Hardware/blob/457a7c18b6985121b64bf2bb87be57ea3d9fad60/Accessories/ExpansionBoard_IO_Converter/REV20210414B/IO_Converter_sch.pdf).

## PCB Layout

| Dimensions |   |
|:------------------------:|:-:|
| Board Size (W x H) | 2.4" x 2.5"|
| Number of Layers | 2 |

Top layer copper routing:
image

Bottom layer copper routing
image

3D view:
image

### Bill of Materials
| Quantity | Designator  | Value | Manufacturer Part Number 1 | Supplier Order Qty 1 |
| ----------| ------------- | ------ | -------------------------------- | ---------------------- |
| 2             | C1, C2         | 1uF    | CL10A105KP8NNWC               | 2                    |
| 4        | C7A, C7B, C9A, C9B  | 1pF  | CC0603BRNPO9BN1R0    | 4                    |
| 4        | C8A, C8B, C10A, C10B        | 16pF      | CC0603JRNPO9BN160          | 4                    |
| 6        | C11, C12, C13, C14, C15, C16     | 0.1uF    | CC0603KRX7R8BB104      | 6                    |
| 1        | CON1   |                   | ICD15S13E6GX00LF           | 1                    |
| 1        | CON2   |                   | 381-009-112L565            | 1                    |
| 1        | CON3   |                   | 1862291                    | 1                    |
| 16       | R7A, R7B, R8A, R8B, R9A, R9B, R11A, R11B, R12A, R12B, R13A, R13B, R14A, R14B, R16A, R16B | 10K               | RT0603DRE0710KL            | 16                   |
| 4 | R10A, R10B, R15A, R15B | 25K | CPF-A-0805B25KE | 4 |
| 22       | TP1, TP2, TP3, TP4, TP5, TP6, TP7, TP8, TP9, TP10, TP11, TP12, TP13, TP14, TP15, TP16, TP17, TP18, TP19, TP20, TP21, TP22 |              |RCU-0C            | 22     |
| 1        | U1      |                   | TLV75533PDBVR              | 1                    |
| 4        | U2A, U2B, U3A, U3B |    | 74LVC2G14GW-Q100H | 4                          |
| 4        | U4, U6, U8, U9 |       | SN74LVC1T45DBVR   | 4                          |
| 1        | U5    |                   | UA9638CDR                  | 1                    |
| 1        | U7        |                   | UA9637ACDR                 | 1                    |

The parts cost about $40 per board at order quantity 1 from Digi-Key.

### CODE REVIEW

**Comment by elsevers** [comment]
We need some documentation on the glitch filter and how the passive components are selected to determine voltage threshold, etc. It looks like we don't yet have this?

**Review by elsevers — CHANGES_REQUESTED** [review]
- [x] Add test points
- [x] Add decoupling capacitors
- [x] Add revision info to `revxxxxx` folder
- [x] work with @GnomeTek and @npetersen2 to update main `readme.md` doc to document glitch filter

**Comment by npetersen2** [comment]
Interesting paper about Cascading Schmitt-Trigger Stages:
https://arxiv.org/pdf/2006.08415.pdf

**Comment by BrandtBuchda** [comment]
I've added the missing bypass capacitors and some more test points after each of the LPFs as per our discussion. If all looks good the board is ready to be ordered.

**Review by npetersen2 — COMMENTED** [review]
Schematic changes seem good -- added test points and decoupling caps.

Just need the documentation now.

**Comment by elsevers** [comment]
> 
> 
> Interesting paper about Cascading Schmitt-Trigger Stages:
> https://arxiv.org/pdf/2006.08415.pdf

Please include this in the markdown documentation

**Comment by BrandtBuchda** [comment]
The documentation can be reviewed [here](https://github.com/Severson-Group/AMDC-Hardware/tree/io_converter_revb_pcb/Accessories/Kaman_IO_ConverterBoard/docs).

**Review by GnomeTek — CHANGES_REQUESTED** [review]
Information included on Glitch Filter design

Suggest changing text color of SVG graphics to a grey or other white/black background compatible color as GitHub now has dark mode and the text of the filter topology graphic cannot be made out.

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@BrandtBuchda can you update your commits to have you as the author? They are appearing as ghost commits now. Perhaps the settings in your git client are not up-to-date?

**Review by elsevers — APPROVED** [review]
Looks good to me.

**Comment by BrandtBuchda** [comment]
> @BrandtBuchda can you update your commits to have you as the author? They are appearing as ghost commits now. Perhaps the settings in your git client are not up-to-date?

My email was set to the incorrect email so I added it to my git account. They should all be linked to my account now.

**Review by npetersen2 — APPROVED** [review]
Thanks @BrandtBuchda, looks good to me.

**Review by GnomeTek — APPROVED** [review]

**Pull request merged**
