### PR TITLE
Schematic and signal layer connections document using `Smart PDF`

### PR DESCRIPTION
**Pull request by purohitparth25**
This PR adds a composite `PDF` document containing schematic diagrams and top and bottom layer connection details in the respective revision folder (`revC` folder). This document is created using the `Smart PDF` feature of the Altium Designer software. Documentation on this feature from Altium can be found [here](https://www.altium.com/documentation/altium-designer/workspacemanager-dlg-smartpdfsmart-pdf-wizard-ad?version=18.1).

### CODE REVIEW

**Comment by purohitparth25** [comment]
@elsevers @npetersen2 

This PR is ready for review now. I have added a composite `PDF` document containing both the schematics and top and bottom layer trace details and the overlays.

**Review by npetersen2 — CHANGES_REQUESTED** [review]
Nice PDF! Can you remove the old PDFs and replace with the new one? Also, I do not think we need two copies of the same PDF. Just keep the PDF in the `REVxxxx` output folder.

**Review by elsevers — CHANGES_REQUESTED** [review]
Thanks @purohitparth25! Can you please revise this to be two separate PDFs:
1. One document for the schematic
2. One document for the PDF.

**Comment by purohitparth25** [comment]
@elsevers @npetersen2 

I just reorganized files as per your comments and this PR is ready to merge now

**Review by npetersen2 — APPROVED** [review]
Looks good to me, thanks @purohitparth25

**Review by elsevers — APPROVED** [review]
Thanks @purohitparth25

**Pull request merged**
