### PR TITLE
[DAC Board] Rev C Final Merge

### LINKED ISSUE #143: DAC board: fix short between Inverter Status A pin and GND
The same DB-15 connector is used for both the Power Stack and IsoSPI interfaces on the DAC board. In the IsoSPI pinout, pin 7 & pin 8 are SPI IP and SPI IM lines respectively and are connect directly to a transformer. In the Power Stack pinout, pin 7 & pin 8 are GND and Inverter Status A respectively..

Status A is shorted through the transformer to GND when using the Power Stack port. A jumper needs to be installed between pin 7 on the DB-15 connector and the transformer pin 16 to isolate the connection.

### LINKED ISSUE #200: DAC board: update connector interface to AMDC
This issue supersedes #143 -- resolving this issue will fix #143

---

The REV B hardware design for the DAC board is designed so that the DAC can be used with either:

- GPIO expansion port (in REV B design, this is referred to as "IsoSPI")
- Power stack port

The REV C hardware design that @codecubepi and @wknutson are working on requires changes to this AMDC interface.

## Required Changes

The REV C DAC is still expected to work with both the GPIO expansion port and the power stack port. However, the hardware interface is now only supporting the latest AMDC hardware, REV E. On AMDC REV E, the GPIO port interface has changed. These changes need to be incorporated into the new DAC board design.

Specifically, the DAC board will no longer have any "isoSPI" hardware on it. All the isoSPI related devices should be deleted.

### AMDC interface

The DAC requires 3 logic wires for the AMDC interface: `CS`, `SCLK` and `SDI` -- these form the SPI interface. For the actual DAC IC, these signals are single-ended and range from 0V to 5V. These 3 signals need to come from the AMDC.

When plugged into the power stack port, the power stack status lines are used for the 3 signals. These status line signals from the AMDC are also single-ended. Therefore, they are directly compatible with the DAC IC.

When plugged into the GPIO expansion port, the 3 output signals are used for the SPI. However, these signals from the AMDC are differential. This means that the DAC board will need a differential-to-single ended converter for this interface.

For both interfaces, the goal of the DAC board is to be isolated from the AMDC. To do this, an isolator is used. See `U1` in the REV B DAC board design. This isolator will remain in the REV C DAC design.

### PR DESCRIPTION
**Pull request by codecubepi**
Final merge of ```dac-rev-c``` into ```develop``` before ordering.

- Schematic Design Review PR: #207 
- PCB Design Review PR: #212 

The ```docs``` folder has been removed and proper documentation is to be updated at [docs.amdc.dev](https://github.com/Severson-Group/docs.amdc.dev)

### CODE REVIEW

**Review by npetersen2 — CHANGES_REQUESTED** [review]
Thanks @codecubepi ! A few comments:

- [x] In the main `README.md` file for the DAC, it still links to the `docs/` folder; please update to point to the docs.amdc.dev website section for the DAC
- [x] I think the contents of `./SCH-Images/` and `./altium/parts/` are the same, if so, can you consolidate? Probably remove your new `SCH-Images/` folder and update altium schematic file links as necessary.
- [x] Add a photo to the top level DAC `README` file landing page, just link to your `PCB_3D_Top.png` file. See the `uInverter` readme for an example.

**Comment by codecubepi** [comment]
@npetersen2 Comments addressed, changes made. Let me know if there's anything else.

**Comment by codecubepi** [comment]
I've also opened a PR on [the docs repo](https://github.com/Severson-Group/docs.amdc.dev/pull/48) to update those to REV C, per the original comment on this PR.

**Review by npetersen2 — DISMISSED** [review]
@codecubepi thanks for your work on this board revision!

Looks good, I am excited to see you build and test the new hardware with both AMDC REV E interfaces! :)

**Review by elsevers — DISMISSED** [review]
Great job

**Review by npetersen2 — APPROVED** [review]

**Pull request merged**
