### PR TITLE
Add silkscreen designator column to BOM

### LINKED ISSUE #216: uInverter: silk-screen designators and schematic designators mismatch
Designators do not match between the schematic and silk screen for many BOM items.
Attached representative image showing mismatch for the decoupling caps.

uInverter_marked
uInverter_InputPower

### PR DESCRIPTION
**Pull request by purohitparth25**
This PR provides a solution to the issue #216 .

In this PR:
- A column named `Silkscreen Designators` is added to the BOM to show the corresponding designator names from the silkscreen

### CODE REVIEW

**Comment by purohitparth25** [comment]
@elsevers @npetersen2
I have added a column to the BOM to show the corresponding designators printed on the silkscreen.

@anirudhupadhyaya @shamagvasisht @mslaffin 
Can either one of you check and confirm if the BOM looks fine or not?

Thanks!

**Review by anirudhupadhyaya — COMMENTED** [review]
Hey Parth, the resistor designators look okay to me. But the capacitor and the testpoint designators still don't match up.

**Comment by purohitparth25** [comment]
> Hey Parth, the resistor designators look okay to me. But the capacitor and the testpoint designators still don't match up.

I changed the order of the designators.

**Comment by purohitparth25** [comment]
@elsevers 
This PR is ready for review

**Comment by purohitparth25** [comment]
@shamagvasisht @mslaffin

Let me know when you are done with verifying the updated BOM file for `rev B`.

**Comment by shamagvasisht** [comment]
> @shamagvasisht @mslaffin
> 
> Let me know when you are done with verifying the updated BOM file for `rev B`.

@purohitparth25 
Verification is done. Everything looks good to me, found one minor change :schematic designator and silkscreen designator for terminal J1 is same, i.e J1 not J2

**Comment by purohitparth25** [comment]
> > @shamagvasisht @mslaffin
> > Let me know when you are done with verifying the updated BOM file for `rev B`.
> 
> @purohitparth25 Verification is done. Everything looks good to me, found one minor change :schematic designator and silkscreen designator for terminal J1 is same, i.e J1 not J2

@shamagvasisht I fixed this.

**Comment by purohitparth25** [comment]
@elsevers This PR is ready to merge now.

**Review by mslaffin — DISMISSED** [review]

**Review by elsevers — CHANGES_REQUESTED** [review]
@purohitparth25, thanks for taking this on and clarifying the silkscreen designator. 

To help future users of the uInverter, can you please edit the [Readme.md file](https://github.com/Severson-Group/AMDC-Hardware/tree/revB_fix/Accessories/ExpansionBoard_uInverter/REV20220329B) in the [`REV20220329B`](https://github.com/Severson-Group/AMDC-Hardware/tree/revB_fix/Accessories/ExpansionBoard_uInverter/REV20220329B) folder to provide narrative explaining:
- that the component designator on the PCB does not match the designator indicated on the schematic and link to issue #216
- that the `uint_revB_BOM.csv` contains columns that explain how the PCB designators correspond to the schematic designators

**Comment by purohitparth25** [comment]
> * plain how the PCB designators correspond to the schematic desi

Done

**Comment by purohitparth25** [comment]
> @purohitparth25, thanks for taking this on and clarifying the silkscreen designator.
> 
> To help future users of the uInverter, can you please edit the [Readme.md file](https://github.com/Severson-Group/AMDC-Hardware/tree/revB_fix/Accessories/ExpansionBoard_uInverter/REV20220329B) in the [`REV20220329B`](https://github.com/Severson-Group/AMDC-Hardware/tree/revB_fix/Accessories/ExpansionBoard_uInverter/REV20220329B) folder to provide narrative explaining:
> 
> * that the component designator on the PCB does not match the designator indicated on the schematic and link to issue #216
> * that the `uint_revB_BOM.csv` contains columns that explain how the PCB designators correspond to the schematic designators

Done

**Review by elsevers — APPROVED** [review]
Looks good, thanks @purohitparth25!

**Pull request merged**
