### PR TITLE
REV D development

### PR DESCRIPTION
**Pull request by npetersen2**
This PR brings repo `develop` branch up to the latest and greatest, REV D. Once the REV D design is finalized, frozen, and ordered, we will merge this PR.

### CODE REVIEW

**Comment by npetersen2** [comment]
@elsevers Please approve this PR for merging all the REV D design work into `develop`.

**Comment by elsevers** [comment]
Do you mean to have the `REV20200129D/ScreamingCircuits` folder in here? 

There also is a `REV20200129D/ScreamingCircuits.zip` file

**Comment by npetersen2** [comment]
Yes, the `ScreamingCircuits` folder is the "gerbers" that were sent to manufacturing (actually odb files, stack-up info, BOM, etc). I suppose we don't need the zip file in git, but I like having it since it was ACTUALLY what was sent out. That way, there is no question what info they received.

**Review by elsevers — CHANGES_REQUESTED** [review]
Please remove zip file and add readme explaining how to order boards from Screaming Circuits.

**Comment by npetersen2** [comment]
@elsevers I have completed your requested changes, please approve and merge.

**Review by elsevers — APPROVED** [review]
Looks great.

**Pull request merged**
