### PR TITLE
[Kaman IO Converter Board] Rev C Design Review

### LINKED ISSUE #218: Kaman I/O Board: Add diff I/O termination resistors
## Issue Description

The I/O between the AMDC and the Kaman adapter board is differential. However, there is no termination resistors on the signals, either on the AMDC or the Kaman adapter board. This causes ringing and voltage overshoots. The datasheet highly recommends a termination resistor of 80-120 ohms.

## Changes Requested

Add four termination resistors to the Kaman adapter board design. Attach between the `_P` and `_N` signals:

image

## Hardware Testing Results

Here are a few scope captures of the original board with no termination resistors, and then with added termination resistors of ~120 ohms. All captures are the raw diff I/O, so you will see a nominal polarity and the negated polarity.

In the captures below, `C8` is always the filtered `CNV_n` signal to the Kaman sensors. The `CNV_n` falling edge triggers the ADC sampling.

### 1. `CNV_n` signal

gpio2--00002

gpio2--00003

### 2. `SCK` signal

gpio2--00000

gpio2--00001

### 3. `CNV_n` signal, with termination resistor

gpio2--00014

gpio2--00015

### 4. `SCK` signal, with termination resistor

gpio2--00012

gpio2--00013

### PR DESCRIPTION
**Pull request by o-liv-ia**
# Revision C Overview 

This PR is for the first Design Review of Rev C of the Kaman IO Converter Board, to approve the PCB design before merging in `develop` and ordering the board. 

This PR addresses Issue #218 .

The major fix addressed in the Revision C design is the addition of termination resistors to the N and P lines. 

## Final Schematics -
[IO_Converter_Board_Sch.pdf](https://github.com/Severson-Group/AMDC-Hardware/files/10734386/IO_Converter_Board_Sch.pdf)

## New Termination Resistors- 
new_resistors

## PCB 3D Captures- see R17, R18, R19, R20
pcb_bottom

## BOM- 
The estimated cost to order the parts for this board is $51.19 and the estimated cost for the board itself is $28.64 for 5 boards from pcbway. 
[IO_Converter_Board_BOM.csv](https://github.com/Severson-Group/AMDC-Hardware/files/10745101/IO_Converter_Board_BOM.csv)

### CODE REVIEW

**Comment by npetersen2** [comment]
Thanks @o-liv-ia ! Can you update the description to link any relevant issues you are solving here? And then add it to the GitHub PR so that everything is linked. Probably just #218 but check if any other issues related to the Kaman converter board make sense to close when this PR is merged.

See this PR for example: https://github.com/Severson-Group/AMDC-Hardware/pull/217

image

image

**Review by npetersen2 — CHANGES_REQUESTED** [review]
@o-liv-ia thanks!

A small request:
- [x] Can you flip around the silk screen for the designator for the R18 and R20 to match the direction of the other text on the bottom of the board?

Overall, looks great! Can you please generate the `REVxxxx/` folder with the appropriate files (gerbers, drill file, BOM csv, schematic pdf, and board screen shot)? You can add those to this PR and then re-request my review. Once that's done, let's order the boards and merge the PR!

**Comment by o-liv-ia** [comment]
@elsevers @npetersen2 This board is ready for review and order!

**Review by npetersen2 — COMMENTED** [review]
Looks good to me!

Let's wait until @elsevers approves to merge. Then, let's order some hardware!

**Review by npetersen2 — APPROVED** [review]

**Pull request merged**
